ui: tape
browsers:
  - name: android
    version: latest
  - name: iphone
    version: 4..latest
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: ie
    version: 9..latest
